export const data = [
    {
        id:'1',
        name:'Qaiser',
        email:'qaiserh844@gmail.com',
        department:'Technology',
        phone:'030127098842'
    },
    {
        id:'2',
        name:'Muttahar',
        email:'Muttahar@gmail.com',
        department:'Technology',
        phone:'030127098842'
    },
    {
        id:'3',
        name:'zeeshan',
        email:'zeeshan@gmail.com',
        department:'Technology',
        phone:'030127098842'
    },
    {
        id:'4',
        name:'muzammil',
        email:'muzammil@gmail.com',
        department:'Technology',
        phone:'030127098842'
    },
    {
        id:'5',
        name:'owais',
        email:'owais@gmail.com',
        department:'Technology',
        phone:'030127098842'
    },
    {
        id:'6',
        name:'kamran',
        email:'kamran@gmail.com',
        department:'Technology',
        phone:'030127098842'
    },
    {
        id:'7',
        name:'Ali raza',
        email:'razaAli@gmail.com',
        department:'Technology',
        phone:'030127098842'
    },
    {
        id:'8',
        name:'shabana',
        email:'shabana@gmail.com',
        department:'Technology',
        phone:'030127098842'
    },
    {
        id:'9',
        name:'tabbassum',
        email:'tabassum@gmail.com',
        department:'Technology',
        phone:'030127098842'
    },
    {
        id:'10',
        name:'rameez',
        email:'rameez@gmail.com',
        department:'Technology',
        phone:'030127098842'
    },
    {
        id:'11',
        name:'bilal',
        email:'bilal@gmail.com',
        department:'Technology',
        phone:'030127098842'
    },
    {
        id:'12',
        name:'summaiya',
        email:'summaiya@gmail.com',
        department:'Technology',
        phone:'030127098842'
    },
]